
name: Build Release Installer

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish self-contained app
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish /p:InvariantGlobalization=true

      - name: Zip published output
        run: Compress-Archive -Path publish\* -DestinationPath MornyMorse-win-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MornyMorse-win-x64
          path: MornyMorse-win-x64.zip

      # Optional: Create a GitHub Release and upload the installer
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: MornyMorse-win-x64.zip
